"use client"

import { Inter } from "next/font/google"
import Link from "next/link"
import { Layout, Menu } from "antd"
import { AntdRegistry } from "@ant-design/nextjs-registry"
import { SolutionOutlined, UserOutlined } from "@ant-design/icons"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

const { Header, Content, Footer, Sider } = Layout

// export const metadata = {
//   title: "Blindeed",
//   description: "Generated by create next app",
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <Layout style={{ minHeight: "100vh" }}>
            <Sider>
              <div className="flex justify-center items-center p-5 text-2xl text-white font-bold">
                Blindeed
              </div>
              <Menu
                mode="inline"
                theme="dark"
                items={[
                  {
                    label: <Link href="/mypage">My Page</Link>,
                    key: "mypage",
                    icon: <UserOutlined />,
                  },
                  {
                    label: <Link href="/">Polls</Link>,
                    key: "polls",
                    icon: <SolutionOutlined />,
                  },
                ]}
              />
            </Sider>
            <Layout>
              {/* <Header style={{ background: "white" }}>Blindeed</Header> */}
              <Content className="p-4">
                <div className="bg-white rounded p-3">{children}</div>
              </Content>
            </Layout>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  )
}
